--CREATE TABLESPACE for user
CREATE TABLESPACE "test" DATAFILE '/u01/app/oracle/oradata/XE/test.dbf' SIZE 500M AUTOEXTEND ON NEXT 100M MAXSIZE 1G LOGGING ONLINE PERMANENT BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT NOCOMPRESS SEGMENT SPACE MANAGEMENT AUTO;
--CREATE USER
CREATE USER test IDENTIFIED BY test;
-- USER SQL
ALTER USER test DEFAULT TABLESPACE "test" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK ;
-- QUOTA for user on TABLESPACE
ALTER USER test QUOTA UNLIMITED ON "test";
GRANT ALL on "MDSYS"."ALL_SDO_GEOM_METADATA" to test ;
GRANT CREATE SESSION TO test ;
GRANT CREATE VIEW TO test;
GRANT CONNECT, RESOURCE TO test;
