BEGIN;

DROP TABLE river_axes;
DROP SEQUENCE RIVER_AXES_ID_SEQ;

DROP TABLE river_axes_km;
DROP SEQUENCE RIVER_AXES_KM_ID_SEQ;

DROP TABLE cross_section_tracks;
DROP SEQUENCE CROSS_SECTION_TRACKS_ID_SEQ;

DROP TABLE buildings;
DROP SEQUENCE BUILDINGS_ID_SEQ;

DROP TABLE fixpoints;
DROP SEQUENCE FIXPOINTS_ID_SEQ;

DROP TABLE floodplain;
DROP SEQUENCE FLOODPLAIN_ID_SEQ;

DROP TABLE dem;
DROP SEQUENCE DEM_ID_SEQ;

DROP TABLE hws_points;
DROP SEQUENCE HWS_POINTS_ID_SEQ;

DROP TABLE hws_lines;
DROP SEQUENCE HWS_LINES_ID_SEQ;

DROP TABLE floodmaps;
DROP SEQUENCE FLOODMAPS_ID_SEQ;

DROP TABLE hydr_boundaries;
DROP SEQUENCE HYDR_BOUNDARIES_ID_SEQ;

DROP TABLE hydr_boundaries_poly;
DROP SEQUENCE HYDR_BOUNDARIES_POLY_ID_SEQ;

DROP TABLE fed_states;
DROP TABLE hws_kinds;
DROP TABLE sobek_kinds;
DROP TABLE sectie_kinds;
DROP TABLE boundary_kinds;
DROP TABLE axis_kinds;
DROP TABLE building_kinds;

COMMIT;
